services:
  #specify the container we want to run
  assistant:
    container_name: assistant
    env_file:
      - apps/assistant/.env
    build:
      #where we want to run the Docker build from
      context: .
      #Specify the dockerfile path
      dockerfile: ./apps/assistant/Dockerfile
      target: development
    #use to overwrite the command CMD inside the Dockerfile - remember to specify the app
    command: npm run start:dev assistant
    #specify port to connect
    #mounts whole project to the absolute usr/src/app directory
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
  
  connector:
    container_name: connector
    env_file:
      - apps/connector/.env
    build:
      #where we want to run the Docker build from
      context: .
        #Specify the dockerfile path
      dockerfile: ./apps/connector/Dockerfile
      target: development
    #use to overwrite the command CMD inside the Dockerfile - remember to specify the app
    command: npm run start:dev connector
    #specify port to connect
    ports:
      - '5000:5000'
    #mounts whole project to the absolute usr/src/app directory
    volumes:
      - .:/usr/src/app

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: strongpassword

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_for_n8n
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      N8N_HOST: 0.0.0.0
      N8N_PROTOCOL: http
      N8N_PORT: 5678
      N8N_DATABASE_TYPE: postgres
      N8N_DATABASE_HOST: postgres
      N8N_DATABASE_PORT: 5432
      N8N_DATABASE_USER: postgres
      N8N_DATABASE_PASSWORD: postgres
      N8N_DATABASE_NAME: postgres_for_n8n
      N8N_RUNNERS_ENABLED: true
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_data:
